name: Daily Bonus

on:
  schedule:
    - cron: '30 23 * * *'
  workflow_dispatch:

jobs:
  checkin:
    runs-on: ubuntu-latest

    env:
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}
      BILIBILI_COOKIES: ${{ secrets.BILIBILI_COOKIES }}
      YAMIBO_COOKIES: ${{ secrets.YAMIBO_COOKIES }}
      YURIFANS_EMAIL: ${{ secrets.YURIFANS_EMAIL }}
      YURIFANS_PASSWORD: ${{ secrets.YURIFANS_PASSWORD }}
      PICA_USERNAME: ${{ secrets.PICA_USERNAME }}
      PICA_PASSWORD: ${{ secrets.PICA_PASSWORD }}
      UMA_COOKIES: ${{ secrets.UMA_COOKIES }}
      FFXIV_USERNAME: ${{ secrets.FFXIV_USERNAME }}
      FFXIV_PASSWORD: ${{ secrets.FFXIV_PASSWORD }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Set timezone
        run: sudo timedatectl set-timezone 'Asia/Shanghai'

      - name: Echo current time
        run: timedatectl

      - name: Install uv and Python 3.13
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: uv sync

      - name: Check-in
        run: uv run python ./message.py
